name: C Test

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Kodu İndir
        uses: actions/checkout@v2

      - name: Dizin Kontrolü
        run: ls -la  

      - name: C Derleme
        run: gcc C:\Users\kaana\OneDrive\Masaüstü\CodeBlocks\kodlama\sunumicin\test_ders_notu.c

      - name: Testleri Çalıştır
        run: ./test_program  
