name: C Test

on:
  push:
    branches:
      - master  # Master branch'ine yapılan her push tetiklenecek
  pull_request:
    branches:
      - master  # Master branch'ine yapılan pull request'lerde de çalışacak

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions işlemi, Ubuntu en son sürümünde çalışacak

    steps:
      - name: Kodu İndir
        uses: actions/checkout@v2  # Repository'yi indiriyoruz (code checkout)

      # Dosya yapısını kontrol etmek için
      - name: Dosya Yapısını Listele
        run: ls -R  # Tüm dizin ve dosyaları listele, test_ders_notu.c dosyasının burada olduğuna emin olun

      # C Derleme komutu - Dosya yolu düzeltildi
      - name: C Derleme
        run: gcc test_ders_notu.c -o test_program  # test_ders_notu.c'nin repo kök dizininde olduğunu varsayıyoruz

      - name: Testleri Çalıştır
        run: ./test_program  # Derlenen programı çalıştırıyoruz
